repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: .*\.py$
      - id: end-of-file-fixer
        files: .*\.py$
      - id: check-merge-conflict
        files: .*\.py$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [ --fix ,--config=pyproject.toml]
      - id: ruff-format
