[project]
name = "totem"
version = "0.1.0"
description = "Generate Temporal Object Type Models (TOTeM) to uncover type-level temporal and cardinality relations in event logs"
readme = "README.md"
authors = [
    { name = "Görkem-Emre Öztürk", email = "goerkem.emre.oeztuerk@gmail.com" },
]
maintainers = [
    { name = "Görkem-Emre Öztürk", email = "goerkem.emre.oeztuerk@gmail.com" },
]
license = { text = "MIT" }
requires-python = ">=3.13"
dependencies = [
    "ocelescope",
]

[dependency-groups]
dev = ["black>=25.1.0", "pre-commit>=4.2.0", "ruff>=0.12.7"]


[tool.uv.sources]
ocelescope = { git = "https://github.com/rwth-pads/ocelescope.git", subdirectory = "src/ocelescope" }

[tool.ty]
# All rules are enabled as "error" by default; no need to specify unless overriding.
# Example override: relax a rule for the entire project (uncomment if needed).
# rules.TY015 = "warn"  # For invalid-argument-type, warn instead of error.

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]

[tool.uv]
package = true

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
